# frozen_string_literal: true

module Covenant
  module Handlers

    class ContractHandler
      def initialize: (Contracts::IContract contract) {() -> void} -> void

      def call: (untyped args) -> Runtime::ExecutionResult

      private

      attr_reader contract: Contracts::IContract
      attr_reader handler: Proc
    end

    class PipeHandler
      def initialize: (*Proc handlers) -> void

      def call: (untyped input) -> untyped

      private

      attr_reader handlers: Array[Proc]
    end

    def self.pipe: (*Proc handlers) -> PipeHandler
  end
end